### REGISTER

POST http://localhost:5000/auth/register
content-type: application/json

{
  "fullName": "Test test",
  "email": "testAdmin@test.com",
  "role": "user",
  "password": "1234567890",
  "imageUrl": "me.jpg",
  "image": "img.jpg",
  "comments": []
}

### LOGIN

POST http://localhost:5000/auth/login
content-type: application/json

{
  "email": "mosh@gmail.com",
  "password": "123123123"
}

### REFRESH TOKEN

GET http://localhost:5000/auth/refresh
Content-Type: application/json
Authorization: JWT 

### POST 

POST http://localhost:5000/posts
Content-Type: application/json
Authorization: JWT 

{
  "ownerId": "GOING_TO_BE_REPLACED_ID",
  "tmdbId": "109445",
  "tmdbTitle": "Frozen",
  "tmdbImageUrl": "https://image.tmdb.org/t/p/w500/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg",
  "text": "This movie is great for the kids",
  "imageUrl": "https://m.media-amazon.com/images/I/91dK48LufIL._SL1500_.jpg",
  "rating": 4
}

### COMMENT 

POST http://localhost:5000/comments
Content-Type: application/json
Authorization: JWT 

{
  "ownerId": "GOING_TO_BE_REPLACED_ID",
  "postId": "65902cf0d5535e2e07bfc103",
  "text": "xxxxxx"
}

### LOGOUT

GET http://localhost:5000/auth/logout
Content-Type: application/json
Authorization: JWT 
### USER

GET http://localhost:5000/user
Content-Type: application/json
Authorization: JWT 

### RECENT POSTS
GET http://localhost:5000/posts/recent
Content-Type: application/json

### TOP RATED POSTS
GET http://localhost:5000/posts/top-rated
Content-Type: application/json

### MOST COMMENTED POSTS
GET http://localhost:5000/posts/most-commented
Content-Type: application/json