### REGISTER

POST http://localhost:5000/auth/register
content-type: application/json

{
  "firstName": "Test",
  "lastName": "test",
  "email": "testAdmin@test.com",
  "role": "admin",
  "password": "1234567890",
  "passwordConfirm": "1234567890",
  "image": "img.jpg",
  "comments": []
}

### LOGIN

POST http://localhost:5000/auth/login
content-type: application/json

{
  "email": "testAdmin@test.com",
  "password": "1234567890"
}

### REFRESH TOKEN

GET http://localhost:5000/auth/refresh
Content-Type: application/json
Authorization: JWT 

### POST 

POST http://localhost:5000/posts
Content-Type: application/json
Authorization: JWT 

{
  "ownerId": "GOING_TO_BE_REPLACED_ID",
  "tmdbId": "123",
  "text": "Test post with Google user",
  "image": "test.jpg",
  "rating": 5,
  "comments": []
}

### LOGOUT

GET http://localhost:5000/auth/logout
Content-Type: application/json
Authorization: JWT 

### USER

GET http://localhost:5000/user
Content-Type: application/json
Authorization: JWT 